---
title: "Books that have changed my mind"
description: "An update on some influential readings from the last few years."
author: "Joshua Loftus"
date: "01-02-2023"
---

This post contains a selection from my more complete reading lists on Goodreads from [2021](https://www.goodreads.com/user/year_in_books/2021/114412204) and [2022](https://www.goodreads.com/user/year_in_books/2022/114412204).

## Fiction

I started it long ago but finally finished **[The Tin Drum](https://en.wikipedia.org/wiki/The_Tin_Drum)**. What most impressed me from this book was its very peculiar, opinionated view of heroism. In the face of the absurdity of war and arbitrariness of life and fate, characters could be heroic simply by being their own weird self with absolute conviction.

Something similar appealed to me in both the fiction (**The Morningstar**) and autobiography (**My Struggle** book one, so far) of [Knausgaard](https://en.wikipedia.org/wiki/Karl_Ove_Knausg%C3%A5rd). There is self-doubt mixed with the conviction, but there is also an unflinching honesty. A refusal to look away from the least flattering, or even least significant visions of himself or others. The writing transitions between mundane experiences and major life events. Any moment, and any subject, can be expanded to any significance if we choose to keep our focus on it.

**Moby Dick**! The reading by the late William Hootkins was such a joy, one of the best narrations I've ever heard. I was shocked to learn Melville had little success as a writer during his life. This is one of those books that I feel is partly wasted on the young-- it has depths that mature readers can appreciate.

**Don Quixote** is also both hilarious and profound. The ending really changed the whole character of the book and leaves me still unsure what to think about it. Quixote's constant use of "enchanters" as a monocausal explanation for anything that goes wrong or doesn't make sense is a valuable lesson. I find myself remembering this whenever I become focused on any simple explanation for anything. I'll be nodding in agreement and convinced I understand, but then I'll think, "Wait, is this... enchanters?"

I started reading James Joyce. I found much to identify with in **[Portrait](https://en.wikipedia.org/wiki/A_Portrait_of_the_Artist_as_a_Young_Man)**, like the depiction of religious guilt as institutionalized emotional abuse of children. Language, and culture generally, are like forces colonizing our thoughts. Reading Joyce has been like therapy, somehow? I had to practice letting my mind go with the flow to appreciate **[Ulysses](https://en.wikipedia.org/wiki/Ulysses_(novel))**. 

**Zen and the Art of Motorcycle Maintenance** got me interested in ideas about quality, virtues, and what I would now describe as value pluralism. Take art, for example. Is some art better, or is it just a matter of subjective and arbitrary taste? I'm usually subjectivist and democratic, but I'm really conflicted because I think there is something "real" and not entirely observer-dependent about quality. I sometimes worry that humanity could become collectively worse off by developing bad tastes.

## Non-fiction

There are standard, popular stories about the origins of civilization. I've read them from sources like Yuval Noah Harari's *Sapiens*. The narrative goes like this: we were hunter gatherers for a long time and evolved psychological and social mechanisms to live in small groups. Then there was an agricultural revolution, and that made us grow larger populations with all kinds of new problems like inequality and war. **[Seeing Like a State](https://en.wikipedia.org/wiki/Seeing_Like_a_State)** and **[The Dawn of Everything](https://en.wikipedia.org/wiki/The_Dawn_of_Everything)** convinced me these stories are oversimplified to the point of being misleading. There is always so much more happening, at every point of time, that doesn't make it into the convenient retrospective narratives.

Another topic that almost nobody understands: evolution. Even ignoring the religious misconceptions, I think the most common secular view is one that replaces intelligent design with unintelligent design and misses the point that *there is no actual design*. The appearance of design is an illusion of selection bias. **[Full House](https://en.wikipedia.org/wiki/Full_House:_The_Spread_of_Excellence_from_Plato_to_Darwin)** and **Darwin's Dangerous Idea** drove this home for me. Dennett is too impressed with the elegance of the design viewpoint as an explanation. (Dawkins and other functionalists may be less wrong about this than Dennett). Gould understood life and how it is truly undirected. Pointless!

It's a humbling intellectual journey to see one foundational narrative after another evaporate into a fog of uncertainty and complexity whenever I look closely at them long enough. On the one hand I'm amazed by how much humanity has learned (and how little of that I know), but on the other I think we've barely even begun to understand what's possible.

(I'm increasingly finding myself frustrated with the shallowness of the treatment that most non-fiction books give their subjects. There's this formulaic style of writing, like an essay or college term paper that's been expanded with more anecdotes, and it's the result of optimization for an attention-starved publishing industry. I'm probably seeing this more in non-fiction because I've been reading fiction classics, but it's probably there in most of the fiction coming out now as well).

In my personal life, **The Sleeping Beauties**, **Burn**, **Exercised**, and **Deep Work** have convinced me I don't really have a grip on my own body and health or work and professional goals. But because of the podcast [Your Life in Process](https://drdianahill.com/your-life-in-process/), and learning about [ACT](https://en.wikipedia.org/wiki/Acceptance_and_commitment_therapy), I'm OK with this. I think I've been changing a lot in the last few years. I've moved away from optimizing, and I hope I'm becoming more kind to both others and myself.

If you found anything interesting or valuable in this I'd be happy to hear your thoughts!