project:
  type: website
  output-dir: docs
  render: 
    - "*.qmd"
    - "!talks/"
  resources: 
    - "talks/"
    - "files/"

website:
  title: "{{< fa solid chart-simple size=large >}} joshua loftus"
  navbar:
    lowercase: true
    right:
      - text: "{{< fa solid house size=large >}} home"
        file: index.qmd
      - text: "{{< fa solid book-open size=large >}} research"
        file: research.qmd
      - text: "{{< fa solid chalkboard size=large >}} teaching"
        file: teaching.qmd
      - text: "{{< fa solid code size=large >}} software"
        file: software.qmd
      - text: "{{< fa solid comment size=large >}} blog"
        file: posts.qmd
      - text: "{{< fa solid user size=large >}} about"
        file: about.qmd
  site-url: http://joshualoftus.com
  open-graph:
    title: "Joshua Loftus: Statistician and Data Scientist"
    description: "Professional academic website and personal blog"
  twitter-card:
    creator: "@joftius"
    title: "Joshua Loftus: Statistician and Data Scientist"
    description: "Professional academic website and personal blog"
    card-style: summary
  google-analytics: "UA-114292497-1"
  
format:
  html:
    cookie_consent:
      style: simple
      type: express
      palette: light
      lang: en
      cookies_policy: url
    citations: false
    theme: 
      light: [litera, custom_light.scss]
      dark: [darkly, custom_dark.scss]
    css: styles.css
    
collections:
  research:
    share: [twitter, linkedin]
    categories: false
  teaching:
    share: [twitter, linkedin]
    categories: false    
  posts:
    share: [twitter, linkedin]
    categories: true
  ms4ds:
    categories: false
  ml4ds:
    categories: false
  talks:
    categories: true
  physics:
    share: [twitter, linkedin]
    categories: true
  math:
    share: [twitter, linkedin]
    categories: true
  creative_commons: CC BY

editor: source
execute: 
  freeze: auto


