---
title: "Talks"
description: |
  Slides from some of my recent talks.
---

| Recent talks                                                                                                                                                                         |
|--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|
| [Causal depth, AI, and value pluralism](./talks/misc_slides/Pragmatism_pluralism_causal_depth.key)                                                                                   |
| [Talk on causal fairness and interpretability](./talks/fairness/slides/causal_fairness_and_IML.html)                                                                                 |
| [Tutorial on causal fairness and interpretability](./talks/fairness/slides/tutorial.html)                                                                                            |
| [International Conference on Statistics and Data Science](./talks/fairness/slides/ICSDS2022.html)                                                                                    |
| [Psychometric Society keynote](./talks/fairness/slides/IMPS2022.html)                                                                                                                |
| [Discussion of Sani, Malinsky, and Shpitser](https://drive.google.com/file/d/1s829R-mS4ndGtWQyWxffR-xKv4W32avd/view) \[[video](https://youtu.be/itnR1xVS4YI)\]                       |
| [Discussion of Panigrahi, MacDonald, and Kessler](./talks/misc_slides/Panigrahi_discussion.html) \[[video](https://drive.google.com/file/d/12s6xznkdTOBqXqPsZAmL338bf-jXopnX/view)\] |
| [Workshop on Race and Racism in Science](./talks/2021-05-04-workshop-on-race-and-racism-in-science/slides/AIbias.html)                                                               |
| [Conference on Machine Learning and Inequality](./talks/2021-04-18-conference-on-machine-learning-and-inequality/slides/causal.html) \[[video](https://youtu.be/0xju3pEbPFE)\]       |
